version: '3.8'

networks:
  t-bot:

services:
  nginx-t-bot:
    image: nginx:1.25.1-alpine
    container_name: nginx-t-bot
    ports:
      - ${LOCAL_WEB_PORT}:${APP_WEB_PORT}
    volumes:
      - ./docker/Nginx/core:/etc/nginx/
      - ${LOCAL_PATH_HOST}:${APP_PATH}
      - ./docker/Nginx/Logs:/var/log/nginx/
      - ./docker/Nginx/html:/usr/share/nginx/html/
    depends_on:
      - php-t-bot
    networks:
      - t-bot

  php-t-bot:
    build:
      context: ./docker/PHP8
      args:
        docker_user: ${DOCKER_USER}
    container_name: php-t-bot
    volumes:
      - ${LOCAL_PATH_HOST}:${APP_PATH}:cached
    networks:
      - t-bot

  redis-t-bot:
    image: redis:7.2-rc-alpine
    command: ["redis-server", "--appendonly", "yes"]
    container_name: redis-t-bot
    ports:
      - ${LOCAL_REDIS_PORT}:${APP_REDIS_PORT}
    networks:
      - t-bot
